name: Tests
on:
  pull_request:
    paths-ignore: ['dist/**', '*.md']
  push:
    branches: [main, 0.9.x, ci]
    paths-ignore: ['dist/**', '*.md']
jobs:
  test:
    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1']
        laravel: [5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*, 9.*]
        exclude:
          - php: '7.3'
            laravel: 9.*
          - php: '7.4'
            laravel: 9.*
          - php: '8.0'
            laravel: 5.5.*
          - php: '8.0'
            laravel: 5.6.*
          - php: '8.0'
            laravel: 5.7.*
          - php: '8.0'
            laravel: 5.8.*
          - php: '8.1'
            laravel: 5.5.*
          - php: '8.1'
            laravel: 5.6.*
          - php: '8.1'
            laravel: 5.7.*
          - php: '8.1'
            laravel: 5.8.*
          - php: '8.1'
            laravel: 6.*
          - php: '8.1'
            laravel: 7.*
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: inotify
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-
            php-${{ matrix.php }}-laravel-
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-
      - run: |
          composer require laravel/framework:"${{ matrix.laravel }}" --no-update --no-interaction
          composer update --prefer-dist --no-interaction
      - run: vendor/bin/phpunit --testdox --colors=always
      - run: npm ci && npm run build
      - run: npm test
