name: Tests

on:
  pull_request:
    paths-ignore: ['dist/**', '*.md']
  push:
    branches: [main, 0.9.x]
    paths-ignore: ['dist/**', '*.md']

jobs:
  test:
    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4]
        laravel: [5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*]
        include:
          - laravel: 5.6.*
            testbench: 3.6.*
            phpunit: 7.*
          - laravel: 5.7.*
            testbench: 3.7.*
            phpunit: 7.*
          - laravel: 5.8.*
            testbench: 3.8.*
            phpunit: 8.*
          - laravel: 6.*
            testbench: 4.*
            phpunit: 9.*
          - laravel: 7.*
            testbench: 5.*
            phpunit: 9.*
          - laravel: 8.*
            testbench: 6.*
            phpunit: 9.*

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-

      - name: Cache npm dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress --no-suggest
          npm install

      - name: Build
        run: npm run build

      - name: Run PHP tests
        run: vendor/bin/phpunit --testdox --colors=always

      - name: Run Javascript tests
        run: npm test


